config/routes.rb
Rails.application.routes.draw do
  


  root 'welcome#index'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :lists do
  	member do
  		get :delete
  	end
  end

  resources :users do
  	member do
  		get :delete
  	end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

	belongs_to :list
	
end

app/models/list.rb
class List < ApplicationRecord

	has_and_belongs_to_many :users
	has_many :items

	scope :sorted, lambda { order("id ASC") }

	
end

app/models/section.rb
class Section < ApplicationRecord

	belongs_to :list
	has_many :items

end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password

	has_and_belongs_to_many :lists

	scope :sorted, lambda { order("id ASC") }

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	layout 'test'
	
	before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout, :menu, :user_new]
  
  def menu
  	#display text and links
  end

  def login
  	# login form
  end

  def attempt_login
  	if params[:username].present? && params[:password].present?
  		found_user = User.where(:user_name => params[:username]).first
  		if found_user
  			authorized_user = found_user.authenticate(params[:password])
  		end
  	end

  	if authorized_user
  		session[:user_id] = authorized_user.id
  		flash[:notice] = "You are now logged in!"
  		redirect_to(users_path)
	else
		flash.now[:notice] = "Incorrect username or password"
		redirect_to('login')
  	end
  end

  def logout
  	session[:user_id] = nil
  	flash[:notice] = 'Logged out'
  	redirect_to(access_login_path)
  end

  def signup
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def confirm_logged_in
  	unless session[:user_id]
  		flash[:notice] = "Please log in."
  		redirect_to(access_login_path)
  	end
  end
  
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  

  layout 'test'
  before_action :confirm_logged_in

  def index
    @lists = User.find(session[:user_id]).lists
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      User.find(session[:user_id]).lists << @list
      redirect_to(lists_path)
    else
      render('new')
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(list_params)
      redirect_to(lists_path(@list))
    else
      render('edit')
    end
  end

  def delete
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    flash[:success] = "List deleted"
    redirect_to(lists_path)
  end


  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 

  layout 'test'
  

  def index
    @users = User.sorted
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to(lists_path)
    else
      render('new')
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
  

   private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :user_name, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	 


	layout 'test'
	before_action :confirm_logged_in
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<% @page_title = "User Login" %>

<div class="login">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:username) %></td>
      <td><%= text_field_tag(:username, params[:username]) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log In") %></td>
    </tr>
  </table>
  <% end %>
  <%= link_to('Sign Up!', new_user_path, :class => 'action signup') %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Sign Up" %>

<div class='signUp'>
	<h2>Sign Up</h2>
	<%= form_for(@user, :url => lists_path, :method => 'post') do |f| %>
	  <table>
	  	<tr>
	      <td><%= label_tag(:first_name) %></td>
	      <td><%= text_field_tag(:first_name) %></td>
	    </tr>
	    <tr>
	      <td><%= label_tag(:last_name) %></td>
	      <td><%= text_field_tag(:last_name) %></td>
	    </tr>
	    <tr>
	      <td><%= label_tag(:email) %></td>
	      <td><%= text_field_tag(:email) %></td>
	    </tr>
	    <tr>
	      <td><%= label_tag(:username) %></td>
	      <td><%= text_field_tag(:username) %></td>
	    </tr>
	    <tr>
	      <td><%= label_tag(:password) %></td>
	      <td><%= password_field_tag(:password) %></td>
	    </tr>
	    <tr>
	      <td>&nbsp;</td>
	      <td><%= submit_tag("Sign Up") %></td>
	    </tr>
	  </table>
  <% end %>
</div>

app/views/demo/index.html.erb
<h1>Hello World</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryList</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div class='headerContainer'>
  		<%= link_to("Grocery List", root_path, :class => 'title') %>
  		<%= link_to("Lists", lists_path, :class => 'navButton') %>
  		<%= link_to("Users", users_path, :class => 'navButton') %>
  		<%= link_to("Logout", access_logout_path, :class => 'navButton') %>
  	</div>
  	<div class='contentContainer'>
	  	<!-- before yield -->
	    <%= yield %>
	    <!-- after yield -->
	</div>
  </body>
</html>

app/views/lists/delete.html.erb
<h1>Lists#delete</h1>
<p>Find me in app/views/lists/delete.html.erb</p>

app/views/lists/edit.html.erb
<%= link_to("<< Back to Lists", lists_path, :class => 'back_link') %>


<div class='lists edit'>
	<h2>Update List</h2>

	<%= form_for(@list) do |f| %>

		<table summary="Lists form fields">
			<tr>
				<th>Name</th>
				<td><%= f.text_field(:name) %></td>
			</tr>
		</table>

		<div class="form-buttons">
			<%= f.submit("Update List") %>
		</div>
	<% end %>

</div>

app/views/lists/index.html.erb
<div class="lists index">
		<h2 class='listsHeader'>Lists</h2>

		<%= link_to("Add New List", new_list_path, :class => 'action new') %>

		<table class="listing" summary "Lists list">
			
			<% @lists.each do |list| %>
			<tr>
				<td><%= link_to(list.name, edit_list_path(list.id), :class => 'action edit') %></td>
				<td>
					<%= form_for(list, :method => 'delete') do |f| %>
						<div class='form-buttons'>
							<%= f.submit("X") %>
						</div>
						<% end %>					
			</tr>
			<% end %>
		</table>
	</div>

app/views/lists/new.html.erb
<%= link_to("<< Back to Lists", lists_path, :class => 'back_link') %>


<div class='lists new'>
	<h2>Create new List</h2>

	<%= form_for(@list, :url => lists_path, :method => 'post') do |f| %>

		<table summary="Lists form fields">
			<tr>
				<th>Name</th>
				<td><%= f.text_field(:name) %></td>
			</tr>
		</table>

		<div class="form-buttons">
			<%= f.submit("Create List") %>
		</div>
	<% end %>

</div>

app/views/lists/show.html.erb
<%= link_to("<< Back to lists", lists_path, :class => 'back button') %>

<h3><%= @list.name%></h3>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="users index">
		<h2>Users</h2>

		<%= link_to("Add New User", '#', :class => 'action new') %>

		<table class="listing" summary "Users user">
			<tr class="header">
				<th>First Name</th>
				<th>Last Name</th>
				<th>User Name</th>
			</tr>

			<% @users.each do |user| %>
			<tr>
				
				<td><%= link_to(user.first_name, user_path(user),:class => 'action show') %></td>
				<td><%= user.last_name%></td>
				<td><%= user.user_name%></td>
				<td>
			</tr>
			<% end %>
		</table>
		
	</div>

app/views/users/new.html.erb
<% @page_title = "Sign Up" %>


<div class='users new'>
	<h2>Sign Up!</h2>

	<%= form_for(@user, :url => users_path, :method => 'post') do |f| %>

		<table summary="Users form fields">
			<tr>
				<th>First Name</th>
				<td><%= f.text_field(:first_name) %></td>
			</tr>
			<tr>
				<th>Last Name</th>
				<td><%= f.text_field(:last_name) %></td>
			</tr>
			<tr>
				<th>email</th>
				<td><%= f.text_field(:email) %></td>
			</tr>
			<tr>
				<th>Username</th>
				<td><%= f.text_field(:user_name) %></td>
			</tr>
			<tr>
				<th>password</th>
				<td><%= f.text_field(:password) %></td>
			</tr>
		</table>

		<div class="form-buttons">
			<%= f.submit("Sign Up!") %>
		</div>
	<% end %>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= link_to("<< Back to Users List", users_path, :class => 'back-link')%>

<h3><%= @user.first_name %></h3>



	<h3><%= @user.lists[0].name %></h3>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>